# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'categoriesView.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CategoriesView(object):
    def setupUi(self, CategoriesView):
        CategoriesView.setObjectName("CategoriesView")
        CategoriesView.resize(763, 563)
        self.btn_create_category = QtWidgets.QPushButton(CategoriesView)
        self.btn_create_category.setGeometry(QtCore.QRect(610, 200, 121, 28))
        self.btn_create_category.setObjectName("btn_create_category")
        self.categories_table = QtWidgets.QTableWidget(CategoriesView)
        self.categories_table.setGeometry(QtCore.QRect(20, 240, 721, 241))
        self.categories_table.setObjectName("categories_table")
        self.categories_table.setColumnCount(1)
        self.categories_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.categories_table.setHorizontalHeaderItem(0, item)
        self.btn_get_all_categories = QtWidgets.QPushButton(CategoriesView)
        self.btn_get_all_categories.setGeometry(QtCore.QRect(30, 200, 161, 28))
        self.btn_get_all_categories.setObjectName("btn_get_all_categories")
        self.ed_category = QtWidgets.QLineEdit(CategoriesView)
        self.ed_category.setGeometry(QtCore.QRect(300, 190, 301, 41))
        self.ed_category.setObjectName("ed_category")
        self.label_3 = QtWidgets.QLabel(CategoriesView)
        self.label_3.setGeometry(QtCore.QRect(290, 60, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(CategoriesView)
        QtCore.QMetaObject.connectSlotsByName(CategoriesView)

    def retranslateUi(self, CategoriesView):
        _translate = QtCore.QCoreApplication.translate
        CategoriesView.setWindowTitle(_translate("CategoriesView", "Dialog"))
        self.btn_create_category.setText(_translate("CategoriesView", "Agregar"))
        item = self.categories_table.horizontalHeaderItem(0)
        item.setText(_translate("CategoriesView", "Nombre"))
        self.btn_get_all_categories.setText(_translate("CategoriesView", "Consultar"))
        self.label_3.setText(_translate("CategoriesView", "CATEGORIAS"))
