# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #12232E, stop:1 #203647);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 771, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#EEFBFB;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 771, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#EEFBFB;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_open_categories = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_categories.setGeometry(QtCore.QRect(330, 280, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_open_categories.setFont(font)
        self.btn_open_categories.setStyleSheet("background-color:#007CC7;\n"
"color:#EEFBFB;")
        self.btn_open_categories.setObjectName("btn_open_categories")
        self.btn_open_atletes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_atletes.setGeometry(QtCore.QRect(330, 340, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_open_atletes.setFont(font)
        self.btn_open_atletes.setStyleSheet("background-color:#007CC7;\n"
"color:#EEFBFB;")
        self.btn_open_atletes.setObjectName("btn_open_atletes")
        self.btn_open_competences = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_competences.setGeometry(QtCore.QRect(330, 400, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_open_competences.setFont(font)
        self.btn_open_competences.setStyleSheet("background-color:#007CC7;\n"
"color:#EEFBFB;")
        self.btn_open_competences.setObjectName("btn_open_competences")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Programa y toma el tiempo de tus competiciones"))
        self.label.setText(_translate("MainWindow", "CROSSFIT TIMER"))
        self.btn_open_categories.setText(_translate("MainWindow", "CATEGORIAS"))
        self.btn_open_atletes.setText(_translate("MainWindow", "REGISTRAR ATLETAS"))
        self.btn_open_competences.setText(_translate("MainWindow", "COMPETENCIAS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
