# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 110, 501, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 30, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_open_categories = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_categories.setGeometry(QtCore.QRect(300, 240, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_open_categories.setFont(font)
        self.btn_open_categories.setObjectName("btn_open_categories")
        self.btn_open_atletes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_atletes.setGeometry(QtCore.QRect(300, 300, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_open_atletes.setFont(font)
        self.btn_open_atletes.setObjectName("btn_open_atletes")
        self.btn_open_competences = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_competences.setGeometry(QtCore.QRect(300, 360, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_open_competences.setFont(font)
        self.btn_open_competences.setObjectName("btn_open_competences")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Programa y toma el tiempo de tus competiciones"))
        self.label.setText(_translate("MainWindow", "CROSSFIT TIMER"))
        self.btn_open_categories.setText(_translate("MainWindow", "CATEGORIAS"))
        self.btn_open_atletes.setText(_translate("MainWindow", "ATLETAS"))
        self.btn_open_competences.setText(_translate("MainWindow", "COMPETENCIAS"))
